#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
codex_root="$(cd -- "${script_dir}/.." && pwd)"
profile_script="${codex_root}/scripts/codex-profile.sh"
manifest_path="${codex_root}/tmp/codex-generated-commands.txt"
target_dir="${HOME}/.local/bin"
quiet="false"
generator_marker='# generated by codex-profile-session-router'

usage() {
  cat <<'EOF'
用法:
  codex-sync-commands.sh [--target-dir DIR] [--quiet]

说明:
  扫描 ~/.codex 下的路由并生成可执行命令到目标目录；路由要么是
  <name>.config.toml 与 auth.json.<name> 成对，要么由 <name>.auth-mode
  （内容为 login）标记为共享登录态路由（无需鉴权文件），例如:
    codex-work
    codex-tmp
    codex-routes
EOF
}

command_name_for_route() {
  local route_name="${1,,}"
  route_name="${route_name//[^a-z0-9._-]/-}"
  while [[ "${route_name}" == *--* ]]; do
    route_name="${route_name//--/-}"
  done
  route_name="${route_name#-}"
  route_name="${route_name%-}"
  if [[ -z "${route_name}" ]]; then
    route_name="default"
  fi
  printf 'codex-%s' "${route_name}"
}

# 登录态路由没有 auth.json.<name>，只认 <name>.auth-mode 这个持久化标记；
# 环境变量 CODEX_PROFILE_AUTH 是一次性的，不能决定是否生成命令。
route_is_login_mode() {
  local mode_file="${codex_root}/${1}.auth-mode"
  [[ -f "${mode_file}" ]] && [[ "$(tr -d '[:space:]' <"${mode_file}")" == "login" ]]
}

print_route_table() {
  local auth_path auth_base base config_path profile
  shopt -s nullglob
  for config_path in "${codex_root}"/*.config.toml; do
    base="${config_path##*/}"
    profile="${base%.config.toml}"
    [[ "${profile}" == route-* ]] && continue
    if [[ "${profile}" == "default" ]]; then
      auth_path="${codex_root}/auth.json"
    else
      auth_path="${codex_root}/auth.json.${profile}"
    fi
    auth_base="${auth_path##*/}"
    if [[ ! -f "${auth_path}" ]]; then
      if route_is_login_mode "${profile}"; then
        auth_base="login"
      else
        continue
      fi
    fi
    printf '%s\t%s\t%s\n' "${profile}" "${base}" "${auth_base}"
  done
  shopt -u nullglob
}

write_wrapper() {
  local wrapper_path="$1"
  shift
  local tmp_path
  tmp_path="$(mktemp "${target_dir}/.codex-wrapper.XXXXXX")"
  {
    printf '%s\n' '#!/usr/bin/env bash'
    printf '%s\n' "${generator_marker}"
    printf 'exec '
    printf '%q ' "$@"
    printf '"$@"\n'
  } > "${tmp_path}"
  chmod 755 "${tmp_path}"
  mv "${tmp_path}" "${wrapper_path}"
}

sync_commands() {
  local auth_base command_name config_base route_name wrapper_path
  local -a current_commands=()

  mkdir -p "${target_dir}"
  mkdir -p "$(dirname -- "${manifest_path}")"

  while IFS=$'\t' read -r route_name config_base auth_base; do
    [[ -n "${route_name}" ]] || continue
    command_name="$(command_name_for_route "${route_name}")"
    wrapper_path="${target_dir}/${command_name}"
    write_wrapper "${wrapper_path}" "${profile_script}" "${route_name}"
    current_commands+=("${command_name}")
  done < <(print_route_table)

  write_wrapper "${target_dir}/codex-routes" "${profile_script}" list
  current_commands+=("codex-routes")

  write_wrapper "${target_dir}/codex-sync-routes" "${script_dir}/codex-sync-commands.sh"
  current_commands+=("codex-sync-routes")

  if [[ -f "${manifest_path}" ]]; then
    while IFS= read -r command_name; do
      [[ -n "${command_name}" ]] || continue
      if [[ " ${current_commands[*]} " == *" ${command_name} "* ]]; then
        continue
      fi
      wrapper_path="${target_dir}/${command_name}"
      if [[ -f "${wrapper_path}" ]] && grep -Fq "${generator_marker}" "${wrapper_path}"; then
        rm -f "${wrapper_path}"
      fi
    done < "${manifest_path}"
  fi

  printf '%s\n' "${current_commands[@]}" > "${manifest_path}"

  if [[ -x "${script_dir}/codex-sync-config.sh" ]]; then
    "${script_dir}/codex-sync-config.sh" --quiet || true
  fi

  if [[ "${quiet}" != "true" ]]; then
    printf '已同步命令到 %s\n' "${target_dir}"
    printf '当前命令:\n'
    printf '  %s\n' "${current_commands[@]}"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target-dir)
      target_dir="${2:-}"
      if [[ -z "${target_dir}" ]]; then
        echo "--target-dir 需要目录参数" >&2
        exit 2
      fi
      shift 2
      ;;
    --quiet)
      quiet="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "未知参数: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

sync_commands
